### ISSUE TITLE
Can't see plot grids

### ISSUE THREAD

**Issue by GMFranceschini** [nicholasehamilton/ggtern#53]
Hi, I am using the package, and it is really useful. However, even with some basic examples, I can't seem to be able to get grids, no matter the theme I use. A colleague of mine tried and also obtained the same result, the plots are ok, but the grids are not visible. Any clue on how I can solve this? R version is 4.1.2

**Comment by wpearman1996** [comment]
I've also had this issue, I noticed that the grid lines are still 'present', but not visible - I was able to make them visible by increasing their size in Adobe Illustrator. Obviously not a great solution, but until this issue is solved it may an be option.

I used the example from: https://www.geo.fu-berlin.de/en/v/soga/Introduction-to-R/Plotting-Data/ternary-diagrams/index.html as well as my own data and had the same issue of no grid lines.

**Comment by GMFranceschini** [comment]
I just noticed that the PDF shows the grid correctly. It's just invisible in RStudio for me. Closing the issue.

**Comment by wbvguo** [comment]
I have the same issue, the plot in Rstudio IDE will not show the grid lines. If we save it into PDF, the plot does have the grid lines, although the color is pretty vague

To make the grid lines more apparent, one can consider to adjust `theme` after calling `theme_showgrid()`, for example

```r
ggtern(df, aes(x, y, z)) + 
  theme_bw() + theme_showgrid() +
  theme(panel.grid.minor = element_line(size = 1, colour = "grey80"), 
        panel.grid.major = element_line(size = 1, colour = "grey30"))
```
